### ISSUE TITLE
panic: Concurrency must be greater than 0 (docker)

### ISSUE THREAD

**Issue by huseyinkogo** [gosom/google-maps-scraper#130]
- Tried to install it to a new system via docker compose
- past 2 months there wasn't a problem
- new system : alpine-docker lxc proxmox
- docker-compose.yml
```
services:
  google-maps-scraper:
    container_name: maps-scraper
    command: '-data-folder /gmapsdata'
    image: gosom/google-maps-scraper
    ports:
      - '5907:8080'
    volumes:
      #- './gmaps-data:/gmapsdata'
      - '/root/google-maps:/gmapsdata'
    restart: unless-stopped
    environment:
      - TZ=Australia/Sydney

```
- the error
```

panic: Concurrency must be greater than 0

goroutine 1 [running]:
github.com/gosom/google-maps-scraper/runner.ParseConfig()
	/app/runner/runner.go:154 +0xea5
main.main()
	/app/main.go:35 +0x125
```
